# Site settings
title: RubyCamp BE 2016
email: rubycamp@rubybelgium.be
url: https://rubycamp.brug.be
description: "RubyCamp Belgium 2016"
gems:
  - jekyll-sitemap

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  primary-bright: '#fff'

# Footer settings
footer: Ruby Belgium

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/brug_be
  - title: github
    url: https://github.com/brug-be/rubycamp

# Build settings
markdown: kramdown
permalink: pretty
